version: '3.8'

services:
  # Main application
  universal-downloader:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - BROWSERLESS_URL=${BROWSERLESS_URL:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      - xvfb
    networks:
      - downloader-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Virtual display for browsers (if not using browserless)
  xvfb:
    image: jlesage/docker-baseimage-gui:v4
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - VNC_PASSWORD=password
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - downloader-network
    restart: unless-stopped

  # Optional: Browserless service for scaled production
  browserless:
    image: browserless/chrome:latest
    ports:
      - "3001:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=10
      - WORKSPACE_DELETE_EXPIRED=true
      - WORKSPACE_EXPIRE_DAYS=1
      - ENABLE_CORS=true
    networks:
      - downloader-network
    restart: unless-stopped
    profiles:
      - browserless

networks:
  downloader-network:
    driver: bridge

volumes:
  x11-socket: