[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"

[resources]
memory = "2Gi"
cpu = "2000m"

[nixpacks]
buildCmd = "npm ci"
startCmd = "npm start"

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/tmp"